/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Habby Garden Palette
        "on-surface": "#26362d",
        "on-secondary": "#e6ffef",
        "on-secondary-fixed-variant": "#006b4b",
        "secondary-dim": "#005f43",
        "on-tertiary-fixed-variant": "#75221f",
        "surface-tint": "#006d50",
        "surface-container-low": "#ebf7ed",
        "error": "#ac3434",
        "background": "#f3fcf3",
        "on-surface-variant": "#526358",
        "secondary-fixed": "#9bf8cd",
        "outline-variant": "#a5b6aa",
        "on-primary": "#e5fff1",
        "primary": "#006d50",
        "surface-dim": "#cbdfd0",
        "primary-fixed": "#94f5cd",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#691a17",
        "inverse-primary": "#9cfed5",
        "on-error": "#fff7f6",
        "on-secondary-fixed": "#004b34",
        "surface-variant": "#d5e7da",
        "surface": "#f3fcf3",
        "secondary-container": "#9bf8cd",
        "tertiary-fixed-dim": "#fd8a80",
        "on-error-container": "#65000b",
        "tertiary-dim": "#8f3630",
        "surface-bright": "#f3fcf3",
        "surface-container-high": "#dcece0",
        "inverse-surface": "#08100b",
        "on-background": "#26362d",
        "secondary-fixed-dim": "#8de9c0",
        "on-primary-container": "#005e44",
        "surface-container": "#e4f1e6",
        "inverse-on-surface": "#969f98",
        "tertiary": "#9e413b",
        "on-primary-fixed-variant": "#00694c",
        "primary-fixed-dim": "#86e7bf",
        "tertiary-fixed": "#ff9f96",
        "error-container": "#f56965",
        "error-dim": "#70030f",
        "secondary": "#006d4d",
        "on-primary-fixed": "#004934",
        "surface-container-highest": "#d5e7da",
        "primary-container": "#94f5cd",
        "tertiary-container": "#ff9f96",
        "outline": "#6e7f73",
        "primary-dim": "#005f45",
        "on-tertiary-fixed": "#490205",
        "on-tertiary": "#fff7f6",
        "on-secondary-container": "#006043"
      },
      fontFamily: {
        romens: ["var(--font-romens)", "sans-serif"], 
        forfelast: ["var(--font-forfelast)", "sans-serif"],
        heqra: ["var(--font-heqra)", "sans-serif"],
        vitta: ["var(--font-vitta)", "sans-serif"],
        forfelast_italic: ["var(--font-forfelast_italic)", "sans-serif"],
        // Mapping your HTML classes to your custom variables
        headline: ["var(--font-romens)", "sans-serif"],
        body: ["var(--font-forfelast)", "sans-serif"],
        label: ["var(--font-vitta)", "sans-serif"]
      }
    },
  },
  plugins: [],
};